### ISSUE TITLE
the Code is finished?

### ISSUE THREAD

**Issue by sofapig** [szy0syz/js-mongoose-adapter#1]
The code is just part of mongodb adapter,it is not implemented for Casbin adapter interface.

**Comment by szy0syz** [comment]
还没的，发现必须要用ts写，这两天在写公司项目，还没来得及写。
最近会完成。

没发现sequelize-adapter有个pre钩子ts转js，失误。😥

**Comment by hsluoyz** [comment]
@sofapig please use this one: https://github.com/elasticio/casbin-mongoose-adapter for now as it's already finished.

**Comment by hsluoyz** [comment]
@sofapig please close this issue if resolved :)
